AY2324S1-CS2113-T17-2/tp

src/test/java/seedu/duke/UiTest.java

Issue #27, Add JUnit Test for UI class

---

src/main/java/seedu/duke/data/Menu.java
src/main/java/seedu/duke/data/dish/Dish.java
src/main/java/seedu/duke/data/dish/Ingredient.java
src/main/java/seedu/duke/ui/Ui.java

Add commonly used methods into classes:
1. Ingredient.java
2. Menu.java
3. Dish.java
4. Ui.java

Edit classes v1.0

---

src/main/java/seedu/duke/ui/Ui.java

Issue 21, Implement Ui message for deleting a menu item

---

src/main/java/seedu/duke/command/AddDishCommand.java
src/main/java/seedu/duke/data/Menu.java
src/main/java/seedu/duke/ui/Ui.java
src/main/java/seedu/duke/ui/UserOutput.java

Implement add dish feature

---

src/main/java/seedu/duke/command/ListIngredientCommand.java
src/main/java/seedu/duke/data/Menu.java
src/main/java/seedu/duke/data/dish/Dish.java
src/main/java/seedu/duke/data/dish/Ingredient.java
src/main/java/seedu/duke/ui/Ui.java

20 UI to list ingredients v1.0

---

src/main/java/seedu/duke/command/DeleteDishCommand.java
src/main/java/seedu/duke/parser/Parser.java
src/main/java/seedu/duke/ui/Ui.java

Task 22, Implement parser support for deleting a dish

---

src/main/java/seedu/duke/command/ListIngredientCommand.java
src/main/java/seedu/duke/parser/Parser.java
src/main/java/seedu/duke/ui/Ui.java

Task 23, Implement parsing support for listing ingredients .

---

src/main/java/seedu/cafectrl/command/EditPriceCommand.java
src/main/java/seedu/cafectrl/data/Menu.java
src/main/java/seedu/cafectrl/data/dish/Dish.java
src/main/java/seedu/cafectrl/parser/Parser.java
src/main/java/seedu/cafectrl/ui/Messages.java
src/main/java/seedu/cafectrl/ui/Ui.java

11 feature edit price v1.0

---

src/main/java/seedu/cafectrl/command/AddDishCommand.java
src/main/java/seedu/cafectrl/parser/Parser.java
src/main/java/seedu/cafectrl/ui/Ui.java

24 parser add dish v1.0

---

src/main/java/seedu/cafectrl/command/DeleteDishCommand.java
src/main/java/seedu/cafectrl/parser/Parser.java
src/main/java/seedu/cafectrl/ui/Messages.java
src/test/java/seedu/cafectrl/command/DeleteDishCommandTest.java
src/test/java/seedu/cafectrl/parser/ParserTest.java

Task 17, Implement delete feature

---

src/test/java/seedu/cafectrl/parser/ParserTest.java

Added JUnit Tests for add dish command parsing

---

src/main/java/seedu/cafectrl/parser/Parser.java

Edit add dish parsing code to prevent negative price input

---

.gitignore
build.gradle

77 enable assertions v1.1

---

src/main/java/seedu/cafectrl/command/AddDishCommand.java
src/main/java/seedu/cafectrl/parser/Parser.java
src/main/java/seedu/cafectrl/ui/Messages.java

102 AddDish Command exception handling v1.1

---

src/main/java/seedu/cafectrl/Order.java
src/main/java/seedu/cafectrl/ui/Messages.java

#84 implement UI support for order class

---

src/main/java/seedu/cafectrl/CafeCtrl.java
src/main/java/seedu/cafectrl/Chef.java
src/main/java/seedu/cafectrl/command/AddDishCommand.java
src/main/java/seedu/cafectrl/command/AddOrderCommand.java
src/main/java/seedu/cafectrl/command/BuyIngredientCommand.java
src/main/java/seedu/cafectrl/command/Command.java
src/main/java/seedu/cafectrl/command/DeleteDishCommand.java
src/main/java/seedu/cafectrl/command/EditPriceCommand.java
src/main/java/seedu/cafectrl/command/ExitCommand.java
src/main/java/seedu/cafectrl/command/HelpCommand.java
src/main/java/seedu/cafectrl/command/IncorrectCommand.java
src/main/java/seedu/cafectrl/command/ListIngredientCommand.java
src/main/java/seedu/cafectrl/command/ListMenuCommand.java
src/main/java/seedu/cafectrl/command/ViewTotalStockCommand.java
src/main/java/seedu/cafectrl/parser/Parser.java
src/main/java/seedu/cafectrl/ui/Messages.java
src/test/java/seedu/cafectrl/command/AddDishCommandTest.java
src/test/java/seedu/cafectrl/command/DeleteDishCommandTest.java
src/test/java/seedu/cafectrl/command/EditPriceCommandTest.java
src/test/java/seedu/cafectrl/command/HelpCommandTest.java
src/test/java/seedu/cafectrl/command/ListIngredientCommandTest.java
src/test/java/seedu/cafectrl/command/ListMenuCommandTest.java
src/test/java/seedu/cafectrl/parser/ParserTest.java

#107 Change Command class execute method

---

src/main/java/seedu/cafectrl/parser/Parser.java
src/test/java/seedu/cafectrl/parser/ParserTest.java

100 format read ingredient unit v1.2

---

src/main/java/seedu/cafectrl/command/BuyIngredientCommand.java
src/main/java/seedu/cafectrl/command/ViewTotalStockCommand.java
src/main/java/seedu/cafectrl/data/Pantry.java
src/main/java/seedu/cafectrl/parser/Parser.java
src/main/java/seedu/cafectrl/ui/Messages.java
src/main/java/seedu/cafectrl/ui/Ui.java
src/test/java/seedu/cafectrl/parser/ParserTest.java

Task 118, Improve buyIngredient command to accept multiple ingredients

---

src/main/java/seedu/cafectrl/parser/Parser.java
src/main/java/seedu/cafectrl/ui/Ui.java

123 refactor add dish v1.2

---

src/main/java/seedu/cafectrl/Order.java

132 Refactor Order Class

---

src/main/java/seedu/cafectrl/command/AddDishCommand.java
src/main/java/seedu/cafectrl/command/BuyIngredientCommand.java
src/main/java/seedu/cafectrl/command/Command.java
src/main/java/seedu/cafectrl/command/DeleteDishCommand.java
src/main/java/seedu/cafectrl/command/EditPriceCommand.java
src/main/java/seedu/cafectrl/command/ExitCommand.java
src/main/java/seedu/cafectrl/command/HelpCommand.java
src/main/java/seedu/cafectrl/command/ViewTotalStockCommand.java
src/main/java/seedu/cafectrl/data/Pantry.java
src/main/java/seedu/cafectrl/parser/Parser.java
src/main/java/seedu/cafectrl/storage/Encoder.java
src/main/java/seedu/cafectrl/ui/Messages.java
src/test/java/seedu/cafectrl/parser/ParserTest.java

149 price float overflow v2.0

---

src/main/java/seedu/cafectrl/CafeCtrl.java
src/main/java/seedu/cafectrl/command/DeleteDishCommand.java
src/main/java/seedu/cafectrl/command/EditPriceCommand.java
src/main/java/seedu/cafectrl/command/HelpCommand.java
src/main/java/seedu/cafectrl/command/ListIngredientCommand.java
src/main/java/seedu/cafectrl/parser/Parser.java
src/main/java/seedu/cafectrl/storage/Decoder.java
src/main/java/seedu/cafectrl/storage/Encoder.java
src/main/java/seedu/cafectrl/storage/FileManager.java
src/main/java/seedu/cafectrl/storage/FilePath.java
src/main/java/seedu/cafectrl/storage/Storage.java
src/main/java/seedu/cafectrl/ui/ErrorMessages.java
src/main/java/seedu/cafectrl/ui/Messages.java
src/main/java/seedu/cafectrl/ui/Ui.java
src/test/java/seedu/cafectrl/command/HelpCommandTest.java
src/test/java/seedu/cafectrl/parser/ParserTest.java
text-ui-test/EXPECTED.TXT

147 encode decode pantry stock

---

src/main/java/seedu/cafectrl/parser/Parser.java
src/main/java/seedu/cafectrl/ui/ErrorMessages.java
src/main/java/seedu/cafectrl/ui/Messages.java
src/test/java/seedu/cafectrl/parser/ParserTest.java

151 same dish name bug v2.0

---

src/main/java/seedu/cafectrl/CafeCtrl.java
src/main/java/seedu/cafectrl/parser/Parser.java
src/main/java/seedu/cafectrl/parser/ParserUtil.java
src/test/java/seedu/cafectrl/parser/ParserTest.java

171 ParserUtil interface

---

src/main/java/seedu/cafectrl/command/AddDishCommand.java
src/main/java/seedu/cafectrl/command/AddOrderCommand.java
src/main/java/seedu/cafectrl/command/BuyIngredientCommand.java
src/main/java/seedu/cafectrl/command/DeleteDishCommand.java
src/main/java/seedu/cafectrl/command/EditPriceCommand.java
src/main/java/seedu/cafectrl/command/ExitCommand.java
src/main/java/seedu/cafectrl/command/HelpCommand.java
src/main/java/seedu/cafectrl/command/ListIngredientCommand.java
src/main/java/seedu/cafectrl/command/ListMenuCommand.java
src/main/java/seedu/cafectrl/command/NextDayCommand.java
src/main/java/seedu/cafectrl/command/PreviousDayCommand.java
src/main/java/seedu/cafectrl/command/ViewTotalStockCommand.java
src/main/java/seedu/cafectrl/ui/Messages.java
src/main/java/seedu/cafectrl/ui/Ui.java
src/test/java/seedu/cafectrl/command/HelpCommandTest.java

Fixes #182 
Move COMMAND_GUIDE from Messages.java to Command classes and standardise the format

182 standardise help command

---

.gitignore
src/main/java/seedu/cafectrl/command/BuyIngredientCommand.java
src/main/java/seedu/cafectrl/parser/Parser.java
src/test/java/seedu/cafectrl/command/BuyIngredientCommandTest.java
src/test/java/seedu/cafectrl/data/PantryTest.java
src/test/java/seedu/cafectrl/parser/ParserTest.java

Task 173, Implement JUnit Test for buyIngredient function

---

src/test/java/seedu/cafectrl/command/ViewTotalStockCommandTest.java
src/test/java/seedu/cafectrl/parser/ParserTest.java

Task 188, Add JUnit test for viewTotalStock command

---

src/main/java/seedu/cafectrl/data/Chef.java
src/main/java/seedu/cafectrl/data/Pantry.java
src/main/java/seedu/cafectrl/ui/Ui.java
src/test/java/seedu/cafectrl/command/AddOrderCommandTest.java

Fix bug for AddOrderCommandTest

---

src/main/java/seedu/cafectrl/command/AddDishCommand.java
src/main/java/seedu/cafectrl/command/AddOrderCommand.java
src/main/java/seedu/cafectrl/command/BuyIngredientCommand.java
src/main/java/seedu/cafectrl/command/EditPriceCommand.java
src/main/java/seedu/cafectrl/command/ViewTotalStockCommand.java
src/main/java/seedu/cafectrl/storage/Decoder.java
src/main/java/seedu/cafectrl/storage/Encoder.java

Debug encoding pantry stock cannot add more than one ingredient

---

docs/DeveloperGuide.md
docs/UserGuide.md
src/main/java/seedu/cafectrl/storage/Decoder.java
src/main/java/seedu/cafectrl/storage/Encoder.java
src/main/java/seedu/cafectrl/ui/Ui.java

216 repeat dish name bug v2.0

---

src/main/java/seedu/cafectrl/ui/Messages.java
src/main/java/seedu/cafectrl/ui/Ui.java

Update code to maintain menu form

---

src/main/java/seedu/cafectrl/ui/Messages.java

Update Message to remove inconsistency

---

src/main/java/seedu/cafectrl/CafeCtrl.java
src/main/java/seedu/cafectrl/data/CurrentDate.java

Update code to bring user back to latest date accessed

---

docs/UserGuide.md

Edit alignment of feature in ug

---

src/main/java/seedu/cafectrl/data/dish/Dish.java
src/main/java/seedu/cafectrl/parser/Parser.java
src/main/java/seedu/cafectrl/ui/ErrorMessages.java
src/test/java/seedu/cafectrl/parser/ParserTest.java

210 bug fix edit price

---

src/main/java/seedu/cafectrl/command/ShowSalesByDayCommand.java
src/main/java/seedu/cafectrl/ui/Ui.java
src/test/java/seedu/cafectrl/command/HelpCommandTest.java

Add show_sales in help command output

---

docs/UserGuide.md
src/main/java/seedu/cafectrl/parser/Parser.java
src/main/java/seedu/cafectrl/storage/Storage.java
src/main/java/seedu/cafectrl/ui/ErrorMessages.java
src/test/java/seedu/cafectrl/parser/ParserTest.java

Fixes #253 , Fixes #238 , Fixes #231

253 edit price ensure 2dp v2.1

---

docs/diagrams/class/AddOrderCommandClass.puml
src/main/java/seedu/cafectrl/command/ViewTotalStockCommand.java
src/main/java/seedu/cafectrl/ui/Messages.java
src/main/java/seedu/cafectrl/ui/Ui.java
src/test/java/seedu/cafectrl/command/ViewTotalStockCommandTest.java

#225 bug fix show stock not aligned

---

docs/UserGuide.md
src/main/java/seedu/cafectrl/parser/Parser.java
src/main/java/seedu/cafectrl/ui/ErrorMessages.java

Fixes #289 
Fixes #249 
Fixes #251

289 edit messages in add dish v2.1

---

src/main/java/seedu/cafectrl/data/Pantry.java

Refactor calculateMaxDish function in 'Pantry' class to improve code quality and fix minor printing bugs.

Refactor calculateMaxDish function in 'Pantry' class.

---

docs/team/NaychiMin.md

Task 306, Add project portfolio page.

---

.gitignore
docs/AboutUs.md
docs/team/shanicetang.md

Task 305, Add draft PPP and upload About Us picture

---

docs/AboutUs.md

Edit hyperlink for PPP pages

---

src/main/java/seedu/cafectrl/command/ListIngredientCommand.java
src/main/java/seedu/cafectrl/data/dish/Dish.java
src/main/java/seedu/cafectrl/ui/Ui.java

Resolve add dish print bug

---

src/main/java/seedu/cafectrl/command/EditPriceCommand.java
src/main/java/seedu/cafectrl/command/HelpCommand.java
src/main/java/seedu/cafectrl/parser/Parser.java
src/main/java/seedu/cafectrl/storage/Decoder.java
src/main/java/seedu/cafectrl/storage/Encoder.java

#271 Add logger to EditPrice, Help, Decoder and Encoder

---

src/main/java/seedu/cafectrl/data/CurrentDate.java
src/main/java/seedu/cafectrl/data/Sales.java
src/main/java/seedu/cafectrl/storage/Decoder.java
src/main/java/seedu/cafectrl/storage/Storage.java
src/main/java/seedu/cafectrl/ui/Messages.java
src/main/java/seedu/cafectrl/ui/Ui.java
src/test/java/seedu/cafectrl/command/ViewTotalStockCommandTest.java

Bug fix hash string tampered with large number

---

src/main/java/seedu/cafectrl/storage/FileManager.java
src/main/java/seedu/cafectrl/ui/ErrorMessages.java
src/test/java/seedu/cafectrl/UiTest.java
src/test/java/seedu/cafectrl/storage/FileManagerTest.java

Add JUnit tests for file manager

---

docs/team/ziyi105.md

I messed up my source tree ;_; help me approve this pleasee

Sync master

---

docs/DeveloperGuide.md
src/main/java/seedu/cafectrl/ui/ErrorMessages.java

Task 360, Check DG

---

docs/UserGuide.md
src/main/java/seedu/cafectrl/command/ListIngredientCommand.java
src/main/java/seedu/cafectrl/parser/Parser.java
src/test/java/seedu/cafectrl/parser/ParserTest.java

370 change tag of list ingredients v2.1

---

src/main/java/seedu/cafectrl/storage/Decoder.java
src/main/java/seedu/cafectrl/ui/ErrorMessages.java

Task 375, 380 Add additional error handling to decode orders.txt.
